import type { Block, BlockStyle, ReportLayout, TableBlock } from './layout';

export interface GenerateOptions {
  /**
   * Adds data-rb="<block id>" to each block's root element and placeholders for
   * unfinished blocks. Used by the live canvas for click-to-select; saved code omits it.
   */
  annotate?: boolean;
}

export const GENERATED_HEADER =
  '{{!-- Generated by the Report Designer visual builder. Changes here are replaced on the next edit; use "Detach to code" in the Design tab to edit by hand. --}}';

const BASE_CSS = `
.rb-field { margin: 2px 0; }
.rb-field .rb-label { color: #666; margin-right: 6px; }
.rb-table { width: 100%; border-collapse: collapse; }
.rb-table th, .rb-table td { padding: 6px 8px; text-align: left; vertical-align: top; }
.rb-table thead { display: table-header-group; }
.rb-table tr { break-inside: avoid; }
.rb-table .rb-empty { color: #888; font-style: italic; }
.rb-placeholder { padding: 12px; border: 1px dashed #bbb; color: #888; text-align: center; font-size: 12px; }
`.trim();

/** Turns a layout into the Handlebars template stored in the report's `code` field. */
export function generateTemplate(layout: ReportLayout, opts: GenerateOptions = {}): string {
  const css: string[] = [BASE_CSS];
  const body = layout.blocks.map((b) => block(b, css, opts)).filter(Boolean);
  return [GENERATED_HEADER, `<style>\n${css.join('\n')}\n</style>`, ...body].join('\n') + '\n';
}

function block(b: Block, css: string[], opts: GenerateOptions): string {
  const attr = opts.annotate ? ` data-rb="${escapeAttr(b.id)}"` : '';
  const style = styleAttr(b.style);
  switch (b.type) {
    case 'text': {
      const text = template(b.text).replace(/\n/g, '<br>');
      return `<${b.tag}${attr}${style}>${text}</${b.tag}>`;
    }
    case 'field':
      return `<div class="rb-field"${attr}${style}><span class="rb-label">${escapeHtml(b.label)}</span><span class="rb-value">${value(b.value)}</span></div>`;
    case 'table':
      return table(b, attr, style, css, opts);
    case 'image': {
      const align = b.style?.align ?? 'left';
      if (!b.assetId) {
        return opts.annotate ? `<div class="rb-placeholder"${attr}>Image: choose an asset in the inspector</div>` : '';
      }
      const width = b.width ? ` style="width:${b.width}px"` : '';
      return `<div${attr}${styleAttr({ ...b.style, align })}><img src="{{resource '${escapeAttr(b.assetId)}'}}"${width} alt=""></div>`;
    }
    case 'divider':
      return `<hr${attr} style="border:none;border-top:${b.thickness ?? 1}px solid ${cssColor(b.color) ?? '#cccccc'};${marginCss(b.style)}">`;
    case 'spacer':
      return `<div${attr} style="height:${Math.max(0, b.height)}px"></div>`;
  }
}

function table(b: TableBlock, attr: string, style: string, css: string[], opts: GenerateOptions): string {
  if (!PATH.test(b.source.trim()) || !b.columns.length) {
    return opts.annotate ? `<div class="rb-placeholder"${attr}>Table: choose a data source and add columns in the inspector</div>` : '';
  }
  const cls = `rb-t-${b.id.replace(/[^\w-]/g, '')}`;
  const head: string[] = [];
  if (b.headerBackground && cssColor(b.headerBackground)) head.push(`background:${cssColor(b.headerBackground)}`);
  if (b.headerColor && cssColor(b.headerColor)) head.push(`color:${cssColor(b.headerColor)}`);
  if (head.length) css.push(`.${cls} th { ${head.join('; ')}; }`);
  css.push(b.bordered ? `.${cls} th, .${cls} td { border: 1px solid #ccc; }` : `.${cls} th, .${cls} td { border-bottom: 1px solid #ddd; }`);
  if (b.striped) css.push(`.${cls} tbody tr:nth-child(even) td { background: #f7f7f7; }`);

  const align = (a?: string) => (a && a !== 'left' ? ` style="text-align:${a}"` : '');
  const cols = b.columns.some((c) => c.width)
    ? `<colgroup>${b.columns.map((c) => (c.width ? `<col style="width:${escapeAttr(c.width)}">` : '<col>')).join('')}</colgroup>`
    : '';
  const ths = b.columns.map((c) => `<th${align(c.align)}>${escapeHtml(c.header)}</th>`).join('');
  const tds = b.columns.map((c) => `<td${align(c.align)}>${value(c.value)}</td>`).join('');
  const empty = b.emptyText ? `{{else}}\n    <tr><td class="rb-empty" colspan="${b.columns.length}">${escapeHtml(b.emptyText)}</td></tr>\n  ` : '';

  return [
    `<table class="rb-table ${cls}"${attr}${style}>`,
    cols ? `  ${cols}` : '',
    `  <thead><tr>${ths}</tr></thead>`,
    `  <tbody>`,
    `  {{#each ${b.source.trim()}}}`,
    `    <tr>${tds}</tr>`,
    `  ${empty}{{/each}}`,
    `  </tbody>`,
    `</table>`,
  ].filter(Boolean).join('\n');
}

// ---------- values & escaping ----------

const PATH = /^(?:\.\.\/)*(?:@?[A-Za-z_$][\w$-]*)(?:\.[A-Za-z_$][\w$-]*)*$/;

/** A bare path becomes `{{path}}`; a template is kept (text escaped); anything else is literal text. */
export function value(v: string): string {
  const trimmed = v.trim();
  if (!trimmed) return '';
  if (trimmed.includes('{{')) return template(trimmed);
  if (PATH.test(trimmed)) return `{{${trimmed}}}`;
  return escapeHtml(trimmed);
}

/** Escapes HTML in literal text while leaving {{...}} expressions untouched. */
export function template(text: string): string {
  return text
    .split(/(\{\{\{?[\s\S]*?\}?\}\})/)
    .map((part, i) => (i % 2 === 1 ? part : escapeHtml(part)))
    .join('');
}

export function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttr(s: string): string {
  return escapeHtml(s).replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function cssColor(c?: string): string | undefined {
  if (!c) return undefined;
  return /^(#[0-9a-f]{3,8}|[a-z]+|rgba?\([\d\s.,%]+\))$/i.test(c.trim()) ? c.trim() : undefined;
}

function marginCss(s?: BlockStyle): string {
  const out: string[] = [];
  if (s?.marginTop !== undefined) out.push(`margin-top:${s.marginTop}px`);
  if (s?.marginBottom !== undefined) out.push(`margin-bottom:${s.marginBottom}px`);
  return out.join(';');
}

function styleAttr(s?: BlockStyle): string {
  if (!s) return '';
  const out: string[] = [];
  if (s.align && s.align !== 'left') out.push(`text-align:${s.align}`);
  if (s.fontSize) out.push(`font-size:${s.fontSize}px`);
  if (s.bold) out.push('font-weight:bold');
  if (cssColor(s.color)) out.push(`color:${cssColor(s.color)}`);
  const m = marginCss(s);
  if (m) out.push(m);
  return out.length ? ` style="${out.join(';')}"` : '';
}
