spring.application.name=report-server

server.port=8088
server.error.include-message=always
server.error.include-exception=true
server.error.include-binding-errors=always
server.error.include-stacktrace=ON_PARAM
browser.path=temp/linux64-137.0.7151.119/chrome-linux64/chrome
#browser.path=/opt/google/chrome/google-chrome
springdoc.swagger-ui.path=/docs
